const cardData = [
  {
    id: 1,
    tag: "highlight",
    user: "Nattapat",
    img: "https://f.ptcdn.info/412/083/000/s9syby4wpoPF8MiPVJLM-o.jpg",
    avatar: "N",
    toppic: "มาแล้วครับ ต่อทะเบียนพ่วงค่าปรับจรารร...//////////",
    categories: "ยานพาหนะ, กฏหมาย",
  },
  {
    id: 2,
    tag: "Pantip Hitz",
    user: "Mark",
    img: "https://f.ptcdn.info/434/083/000/s9wisspxreuJAM0N2uXi-o.jpg",
    avatar: "M",
    toppic: "ลิซ่า BLACKPINK เข้าร่วมงานปารีสแฟชั่นวีคของ Louis Vuitton",
    categories: "ไอดอล, Lisa, BlackPink, K-pop",
  },
  {
    id: 3,
    tag: "",
    user: "Pantita",
    img: "https://f.ptcdn.info/424/083/000/s9ux7h2gqphkRViOKeJ9Z-o.jpg",
    avatar: "P",
    toppic: "หัวเสาของ Imoco ถดูกาลหน้า คิดใครจะได้ยืนหลักคะ?",
    categories: "กีฬา, volley-ball",
  },
  {
    id: 4,
    tag: "Pantip Pick",
    user: "Jonathan",
    img: "https://f.ptcdn.info/434/083/000/s9wf6offthh6hz7Qk6qu-o.jpg",
    avatar: "J",
    toppic:
      "สรรพากร คืนเงินภาษีแล้ว 1.5 ล้านราย พร้อมยืนยันส่งจดหมายถึงผู้เสียภาษีจริง “ไม่ปลอม”",
    categories: "กฏหมาย",
  },
  {
    id: 5,
    tag: "highlight",
    user: "Nattapat",
    img: "https://f.ptcdn.info/435/083/000/s9wpyuo4iaHffzLT0EzE-o.jpg",
    avatar: "N",
    toppic:
      "Suzuki Ciaz 1.2 GL vs Mitsubishi Attrage 1.2 GLX ตัวไหนประหยัดน้ำมันกว่าครับ ใช้ขับต่างจังหวัดครับ",
    categories: "ยานพาหนะ, เศรษฐกิจ, เทคนิค",
  },
  {
    id: 6,
    tag: "",
    user: "Somchai",
    img: "https://f.ptcdn.info/316/083/000/s9b7arlszmQZTqtfqdmQ-o.jpg",
    avatar: "S",
    toppic:
      "เกาหลีรักเจนนี่! Apartment 404 ครองอันดับ 1 เรตติ้ง Real time บน TVING สูงถึง 60.5% 🥳",
    categories: "ไอดอล, เจนนี่, TV, K-pop",
  },
  {
    id: 7,
    tag: "",
    user: "Somchai",
    img: "https://f.ptcdn.info/242/080/000/rsf5si1oqhzlA3Y11P4rh-o.jpg",
    avatar: "S",
    toppic: "JISOO ‘ FLOWER ’ ชาร์ตเปิดตัววันแรกในเกาหลี",
    categories: "ไอดอล, จีซู, K-pop",
  },
  {
    id: 8,
    tag: "",
    user: "Wanarin",
    img: "https://f.ptcdn.info/424/083/000/s9uw8v7ja7H3K0Yg9D6F-o.jpg",
    avatar: "W",
    toppic: "เมนูง่ายๆ สบายๆ 'ปลากุเลาทอด' หอมๆ",
    categories: "อาหาร, สอนทำอาหาร",
  },
  {
    id: 9,
    tag: "highlight",
    user: "Narin",
    img: "https://f.ptcdn.info/422/083/000/s9uosr2a3gh1gmcB4FFz7-o.png",
    avatar: "N",
    toppic: "สถิติรอบแรกของ Superlega 2023/24",
    categories: "กีฬา, sport",
  },
  {
    id: 10,
    tag: "",
    user: "Somchai",
    img: "https://f.ptcdn.info/316/083/000/s9b7arlszmQZTqtfqdmQ-o.jpg",
    avatar: "S",
    toppic:
      "เกาหลีรักเจนนี่! Apartment 404 ครองอันดับ 1 เรตติ้ง Real time บน TVING สูงถึง 60.5% 🥳",
    categories: "ไอดอล, เจนนี่, TV, K-pop",
  },
  {
    id: 11,
    tag: "",
    user: "สมาชิกหมายเลข 5297130",
    img: "https://f.ptcdn.info/408/083/000/s9rxab7cew2D9hlM6X7C-o.jpg",
    avatar: "ส",
    toppic: "จูยอน THE BOYZ เข้าร่วมงานแฟชั่นโชว์ Balenciaga Winter 2024 ❄️❄️",
    categories: "THE BOYZ (นักร้องนักดนตรี), Balenciaga ",
  },
  {
    id: 12,
    tag: "",
    user: "เจ๊แก้ว คนเก่ง",
    img: "https://f.ptcdn.info/387/083/000/s9nzy4v5dgb9UYfLCtUg-o.jpg",
    avatar: "จ",
    toppic: "กินข้าว กับ น้ำพริกด้วยกันมั้ย",
    categories: "ทำอาหาร, อาหารคาว",
  },
  {
    id: 13,
    tag: "",
    user: "Dr Yui คุยทุกเรื่องผิว",
    img: "https://f.ptcdn.info/351/083/000/s9hz0x1dxsskfGrgeZgwP-o.jpg",
    avatar: "D",
    toppic: "ฉีดยาชา vs ทายาชา เลือกแบบไหนดี??",
    categories: "ความงาม",
  },
  {
    id: 14,
    tag: "highlight",
    user: "มนุษย์ถ้ำนักอ่าน",
    img: "https://f.ptcdn.info/353/083/000/s9i9ry29dq0NP1k100r2z-o.jpg",
    avatar: "ม",
    toppic:
      "รีวิวการ์ตูนแอคชั่นไซไฟ All you need is kill สงครามเอเลี่ยนกับชีวิตติดลูป",
    categories: "การ์ตูน, ภาพยนตร์",
  },
  {
    id: 15,
    tag: "Pantip Pick",
    user: "Willkommen",
    img: "https://f.ptcdn.info/343/083/000/s9gemx3fliMmspb74KZl-o.jpg",
    avatar: "W",
    toppic: ">>Switzerland ไปทิ้งเฟอร์นิเจอร์ชิ้นใหญ่กันค่ะ<<",
    categories: "ชีวิตในต่างแดน, การเลี้ยงลูก",
  },
];

export default cardData;
